language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
env:
    - EXT=memcached
services:
    - redis-server
    - memcached
before_install:
    echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
    - composer install

before_script:
    - curl http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer.phar
script:
    - php php-cs-fixer.phar fix -v --dry-run --diff src
    - "./vendor/bin/phpunit"
